# 开发环境配置文件

server:
  port: 8081     # Springboot占用端口

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver     # 数据库驱动
      url: jdbc:mysql://43.143.4.208:3306/seed?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false     # 数据库链接
      username: root     # 数据库账号
      password: root     # 数据库密码
  redis:
    host: ioc-redis
    port: 16379
    password: R123oo456T      # 密码（默认为空）
    timeout: 6000ms  # 连接超时时长（毫秒）
    lettuce:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接
  devtools:
    restart:
      enabled: true     # 开启热更新
  data:
    mongodb:
      host: 43.143.4.208 #指定MongoDB服务地址
      port: 27017 #指定端口，默认就为27017
      database: article
      authentication-database: admin # 登录认证的逻辑库名
#      username: admin #用户名
#      password: abc123456 #密码

rocketmq:
  # 多个用;隔开
#  name-server: 120.48.19.154:9876;120.48.19.154:9877
  name-server: 192.168.133.56:9876
  producer:
    # 生产组
    group: demo-group
    # 发送消息超时时间，默认 3000
    sendMessageTimeout: 3000
    # 发送消息失败重试次数，默认2
    retryTimesWhenSendFailed: 2
    # 发送异步消息失败重试次数，默认2
    retryTimesWhenSendAsyncFailed: 2

swagger:
  enabled: true